// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI2_I5No9oQqRdExIc9nIe5fEZFxxoQ6I',
    appId: '1:884109506020:web:0d2f9aebf96f25945f83f1',
    messagingSenderId: '884109506020',
    projectId: 'oifood-13cca',
    authDomain: 'oifood-13cca.firebaseapp.com',
    storageBucket: 'oifood-13cca.appspot.com',
    measurementId: 'G-1QE7Z8ETVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOKo4uv3pfwMowid_kpP98URZ0i4UkEzI',
    appId: '1:884109506020:android:deef624e5eaa74f85f83f1',
    messagingSenderId: '884109506020',
    projectId: 'oifood-13cca',
    storageBucket: 'oifood-13cca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzSAb_JMDnn0638JNKpsRyJfOO6gOr7c4',
    appId: '1:884109506020:ios:dca959c400503de55f83f1',
    messagingSenderId: '884109506020',
    projectId: 'oifood-13cca',
    storageBucket: 'oifood-13cca.appspot.com',
    iosClientId: '884109506020-mqh8sfjm47j4d93mi8e2u7unh31o3bhn.apps.googleusercontent.com',
    iosBundleId: 'gr.oifood.oifood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzSAb_JMDnn0638JNKpsRyJfOO6gOr7c4',
    appId: '1:884109506020:ios:dca959c400503de55f83f1',
    messagingSenderId: '884109506020',
    projectId: 'oifood-13cca',
    storageBucket: 'oifood-13cca.appspot.com',
    iosClientId: '884109506020-mqh8sfjm47j4d93mi8e2u7unh31o3bhn.apps.googleusercontent.com',
    iosBundleId: 'gr.oifood.oifood',
  );
}
